{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "ibn-core.fullname" . }}-mtls
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ibn-core.labels" . | nindent 4 }}
    managed-by: istio
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
{{- end }}
