apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ibn-core.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ibn-core.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ibn-core.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ibn-core.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ibn-core.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ibn-core.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "ibn-core.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "ibn-core.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
